# Generated by Django 6.0.4 on 2026-04-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_pricing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='features',
            field=models.TextField(help_text='Har bir feature yangi qatorda yoziladi'),
        ),
    ]
